// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQNA7xSc2CTGtCRzdLwdhMWgYcNTLMLKc',
    appId: '1:654005854244:web:437680deb971d1b707f8b1',
    messagingSenderId: '654005854244',
    projectId: 'eat-meh-kitahack',
    authDomain: 'eat-meh-kitahack.firebaseapp.com',
    storageBucket: 'eat-meh-kitahack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKKdO2WsutoHWfOgWEv6rAYKf7wwqDSTc',
    appId: '1:654005854244:android:ca2f1cc94184e0a607f8b1',
    messagingSenderId: '654005854244',
    projectId: 'eat-meh-kitahack',
    storageBucket: 'eat-meh-kitahack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXUPAAZMjMlWxNb-nXdDijuJ7yE1cWjA',
    appId: '1:654005854244:ios:ee4af8b17c68884307f8b1',
    messagingSenderId: '654005854244',
    projectId: 'eat-meh-kitahack',
    storageBucket: 'eat-meh-kitahack.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXUPAAZMjMlWxNb-nXdDijuJ7yE1cWjA',
    appId: '1:654005854244:ios:ee4af8b17c68884307f8b1',
    messagingSenderId: '654005854244',
    projectId: 'eat-meh-kitahack',
    storageBucket: 'eat-meh-kitahack.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQNA7xSc2CTGtCRzdLwdhMWgYcNTLMLKc',
    appId: '1:654005854244:web:1141b3513fe3519b07f8b1',
    messagingSenderId: '654005854244',
    projectId: 'eat-meh-kitahack',
    authDomain: 'eat-meh-kitahack.firebaseapp.com',
    storageBucket: 'eat-meh-kitahack.firebasestorage.app',
  );
}
